/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.sd.dto;

import edu.cmu.sd.dao.*;
import edu.cmu.sd.factory.*;
import edu.cmu.sd.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Notifications implements Serializable
{
	/** 
	 * This attribute maps to the column id in the notifications table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column text in the notifications table.
	 */
	protected String text;

	/** 
	 * This attribute maps to the column recevier in the notifications table.
	 */
	protected String recevier;

	/** 
	 * This attribute maps to the column requestid in the notifications table.
	 */
	protected int requestid;

	/** 
	 * This attribute maps to the column created in the notifications table.
	 */
	protected Date created;

	/**
	 * Method 'Notifications'
	 * 
	 */
	public Notifications()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getText'
	 * 
	 * @return String
	 */
	public String getText()
	{
		return text;
	}

	/**
	 * Method 'setText'
	 * 
	 * @param text
	 */
	public void setText(String text)
	{
		this.text = text;
	}

	/**
	 * Method 'getRecevier'
	 * 
	 * @return String
	 */
	public String getRecevier()
	{
		return recevier;
	}

	/**
	 * Method 'setRecevier'
	 * 
	 * @param recevier
	 */
	public void setRecevier(String recevier)
	{
		this.recevier = recevier;
	}

	/**
	 * Method 'getRequestid'
	 * 
	 * @return int
	 */
	public int getRequestid()
	{
		return requestid;
	}

	/**
	 * Method 'setRequestid'
	 * 
	 * @param requestid
	 */
	public void setRequestid(int requestid)
	{
		this.requestid = requestid;
	}

	/**
	 * Method 'getCreated'
	 * 
	 * @return Date
	 */
	public Date getCreated()
	{
		return created;
	}

	/**
	 * Method 'setCreated'
	 * 
	 * @param created
	 */
	public void setCreated(Date created)
	{
		this.created = created;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Notifications)) {
			return false;
		}
		
		final Notifications _cast = (Notifications) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (text == null ? _cast.text != text : !text.equals( _cast.text )) {
			return false;
		}
		
		if (recevier == null ? _cast.recevier != recevier : !recevier.equals( _cast.recevier )) {
			return false;
		}
		
		if (requestid != _cast.requestid) {
			return false;
		}
		
		if (created == null ? _cast.created != created : !created.equals( _cast.created )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (text != null) {
			_hashCode = 29 * _hashCode + text.hashCode();
		}
		
		if (recevier != null) {
			_hashCode = 29 * _hashCode + recevier.hashCode();
		}
		
		_hashCode = 29 * _hashCode + requestid;
		if (created != null) {
			_hashCode = 29 * _hashCode + created.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return NotificationsPk
	 */
	public NotificationsPk createPk()
	{
		return new NotificationsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.cmu.sd.dto.Notifications: " );
		ret.append( "id=" + id );
		ret.append( ", text=" + text );
		ret.append( ", recevier=" + recevier );
		ret.append( ", requestid=" + requestid );
		ret.append( ", created=" + created );
		return ret.toString();
	}

}
