/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.sd.dao;

import java.util.Date;
import edu.cmu.sd.dto.*;
import edu.cmu.sd.exceptions.*;

public interface RatingsDao
{
	/** 
	 * Inserts a new row in the ratings table.
	 */
	public RatingsPk insert(Ratings dto) throws RatingsDaoException;

	/** 
	 * Updates a single row in the ratings table.
	 */
	public void update(RatingsPk pk, Ratings dto) throws RatingsDaoException;

	/** 
	 * Deletes a single row in the ratings table.
	 */
	public void delete(RatingsPk pk) throws RatingsDaoException;

	/** 
	 * Returns the rows from the ratings table that matches the specified primary-key value.
	 */
	public Ratings findByPrimaryKey(RatingsPk pk) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'id = :id'.
	 */
	public Ratings findByPrimaryKey(int id) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria ''.
	 */
	public Ratings[] findAll() throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'requester = :requester'.
	 */
	public Ratings[] findByUsers(String requester) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'volunteer = :volunteer'.
	 */
	public Ratings[] findByUsers2(String volunteer) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'requestid = :requestid'.
	 */
	public Ratings[] findByRequest(int requestid) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'id = :id'.
	 */
	public Ratings[] findWhereIdEquals(int id) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'requestid = :requestid'.
	 */
	public Ratings[] findWhereRequestidEquals(int requestid) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'requester = :requester'.
	 */
	public Ratings[] findWhereRequesterEquals(String requester) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'volunteer = :volunteer'.
	 */
	public Ratings[] findWhereVolunteerEquals(String volunteer) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'value = :value'.
	 */
	public Ratings[] findWhereValueEquals(float value) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'text = :text'.
	 */
	public Ratings[] findWhereTextEquals(String text) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the criteria 'created = :created'.
	 */
	public Ratings[] findWhereCreatedEquals(Date created) throws RatingsDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the ratings table that match the specified arbitrary SQL statement
	 */
	public Ratings[] findByDynamicSelect(String sql, Object[] sqlParams) throws RatingsDaoException;

	/** 
	 * Returns all rows from the ratings table that match the specified arbitrary SQL statement
	 */
	public Ratings[] findByDynamicWhere(String sql, Object[] sqlParams) throws RatingsDaoException;

}
