/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.sd.factory;

import java.sql.Connection;
import edu.cmu.sd.dao.*;
import edu.cmu.sd.jdbc.*;

public class MessagesDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return MessagesDao
	 */
	public static MessagesDao create()
	{
		return new MessagesDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return MessagesDao
	 */
	public static MessagesDao create(Connection conn)
	{
		return new MessagesDaoImpl( conn );
	}

}
