/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.cmu.sd.factory;

import java.sql.Connection;
import edu.cmu.sd.dao.*;
import edu.cmu.sd.jdbc.*;

public class RatingsDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return RatingsDao
	 */
	public static RatingsDao create()
	{
		return new RatingsDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return RatingsDao
	 */
	public static RatingsDao create(Connection conn)
	{
		return new RatingsDaoImpl( conn );
	}

}
